services:
  - type: web
    name: risk-report-tool
    env: node
    plan: free
    region: oregon
    buildCommand: |
      npm install
      npm install --prefix client
      npm run build --prefix client
    startCommand: node server/index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: OPENAI_API_KEY
        sync: false
